drop database GameSales;
create database GameSales;
use GameSales;

CREATE TABLE Game (
    GameName VARCHAR(100) UNIQUE NOT NULL,
    Generation TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ReleaseYear SMALLINT UNSIGNED NOT NULL DEFAULT 2000,
    Platform VARCHAR(100) NOT NULL,
    PRIMARY KEY (GameName)
);

CREATE TABLE Rating (
    GameName VARCHAR(100) UNIQUE NOT NULL,
    RatingNumber DECIMAL(2 , 1 ) NOT NULL DEFAULT 0,
    ReviewDate DATE NOT NULL DEFAULt 01/01/2000,
    FOREIGN KEY (GameName) REFERENCES Game (GameName)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE Sales (
    GameName VARCHAR(100) UNIQUE NOT NULL,
    UnitSales INT UNSIGNED NOT NULL,
    AllTimeSales INT UNSIGNED NOT NULL,
    FOREIGN KEY (GameName) REFERENCES Game (GameName)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
